apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: goffity/demo-gitops-web
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
  name: demo-web
  namespace: argocd
spec:
  destination:
    namespace: git-ops
    server: 'https://kubernetes.default.svc'
  source:
    path: web
    repoURL: 'https://github.com/goffity/demo-gitops-k8s.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    syncOptions:
      - "CreateNamespace=true"
    automated:
      prune: true
      selfHeal: true
