apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-ops-api-deployment
  labels:
    app: git-ops-api-deployment
spec:
  selector:
    matchLabels:
      app: git-ops-api
  template:
    metadata:
      labels:
        app: git-ops-api
    spec:
      containers:
        - name: git-ops-api
          image: goffity/demo-gitops-api:0.0.1
          resources:
            equests:
              memory: "32Mi"
              cpu: "0.01"
            limits:
              memory: "128Mi"
              cpu: "0.1"
          imagePullPolicy: Always            
          ports:
            - containerPort: 1323
      restartPolicy: Always